// <auto-generated />
using System;
using IT3045C_FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045C_FinalProject.Migrations
{
    [DbContext(typeof(FpDbContext))]
    partial class FpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045C_FinalProject.Models.Culture", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("BirthCountry")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FirstLanguage")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PrimaryLanguage")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StudentId");

                    b.ToTable("Culture");
                });

            modelBuilder.Entity("IT3045C_FinalProject.Models.Favorites", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("FavoriteAnimal")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FavoriteHobby")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FavoriteSeason")
                        .HasColumnType("int");

                    b.Property<string>("FavoriteStore")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("StudentId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("IT3045C_FinalProject.Models.Opinions", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<bool>("CatsOverDogs")
                        .HasColumnType("bit");

                    b.Property<bool>("IOSOverAdroid")
                        .HasColumnType("bit");

                    b.Property<bool>("PineappleOnPizza")
                        .HasColumnType("bit");

                    b.Property<bool>("PlaystationOverXbox")
                        .HasColumnType("bit");

                    b.HasKey("StudentId");

                    b.ToTable("Opinions");
                });

            modelBuilder.Entity("IT3045C_FinalProject.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Program")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("IT3045C_FinalProject.Models.Culture", b =>
                {
                    b.HasOne("IT3045C_FinalProject.Models.Student", "Student")
                        .WithOne("Culture")
                        .HasForeignKey("IT3045C_FinalProject.Models.Culture", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IT3045C_FinalProject.Models.Favorites", b =>
                {
                    b.HasOne("IT3045C_FinalProject.Models.Student", "Student")
                        .WithOne("Favorites")
                        .HasForeignKey("IT3045C_FinalProject.Models.Favorites", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IT3045C_FinalProject.Models.Opinions", b =>
                {
                    b.HasOne("IT3045C_FinalProject.Models.Student", "Student")
                        .WithOne("Opinions")
                        .HasForeignKey("IT3045C_FinalProject.Models.Opinions", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IT3045C_FinalProject.Models.Student", b =>
                {
                    b.Navigation("Culture");

                    b.Navigation("Favorites");

                    b.Navigation("Opinions");
                });
#pragma warning restore 612, 618
        }
    }
}
